---
title: "Basic Example"
description: "This vignette covers the use of zonal with categorical data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Basic Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE
)
```

```{r setup}
library(zonal)
library(geogrids)
library(dplyr)
```

# Define Area of Interest and Aggregation Units
```{r}
base  = geo_path()
AOI   = AOI::aoi_get(state = "south", county = "all")
plot(AOI$geometry)
```

# Find cached geogrids 
```{r}
lai_files = geo_cache_list() %>% 
  filter(grepl('MOD13A3.006/conus', fullname)) %>% 
  pull(fullname)

soil_files = geo_cache_list() %>% 
  filter(grepl('silt-1m-percent.tif', fullname)) %>% 
  pull(fullname)
```

# Disparate Grids `r emo::ji("sad")`
```{r}
make_grid(lai_files[1])
make_grid(soil_files[1])
```

# Warp LAI to soils and execute Zonal
```{r}
system.time({
  out   = geogrid_warp(lai_files[1], make_grid(soil_files[1]), disk = TRUE)
  w     = zonal::weighting_grid(out, AOI, "geoid")
  oo    = execute_zonal(out, w)
})

head(oo)
```

# Speed with precomputed weights
```{r}
# Assuming the weight grid is precomputed...
system.time({
  out   = geogrid_warp(lai_files[1], make_grid(soil_files[1]), disk = TRUE)
  oo    = execute_zonal(out, w)
})
```

# Results

```{r}
a = merge(AOI, oo)
plot(a['X1.km.monthly.NDVI'], border = FALSE)
```


